version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realms:/opt/keycloak/data/import
    command: start-dev --import-realm
    ports:
      - "8081:8080"

  backend:
    container_name: weblab4-backend
    image: weblab4-backend
    env_file:
      - docker-backend.env
    build:
      context: .
    depends_on:
      - postgres
      - keycloak
    ports:
      - "8080:8080"

  frontend:
    container_name: weblab4-frontend
    image: weblab4-frontend
    build:
      context: ./weblabFourth
    depends_on:
      - backend
    ports:
      - "4200:4200"
